Inception Time model for time series classification
IBM/sail pull request #21
Opened 2022-05-26 17:15 UTC by Christosc96

2022-05-27 10:14 UTC, dhavalsalwala requested changes
Hi @Christosc96 ,
Thanks for submitting the PR.

Can you please rename the test file to test_inceptiontime.py? Also, if you have a demo notebook, could you upload it to sail/notebooks?

2022-05-27 23:34 UTC, dhavalsalwala requested changes
Hi @Christosc96 ,

Your unit test is failing. Could you please check?
tests/models/torch/test_inceptiontime.py

2022-05-28 11:00 UTC, Christosc96 commented
Hi @dhavalsalwala, I noticed I the classifier import statement was incorrect and fixed it. The tests do not fail when I try to run them locally (I provide the data in the test file though through a method which I do not include here to be consistent with the reference test file for the rnn classifier).

2022-05-31 14:15 UTC, dhavalsalwala commented
> Hi @dhavalsalwala, I noticed I the classifier import statement was incorrect and fixed it. The tests do not fail when I try to run them locally (I provide the data in the test file though through a method which I do not include here to be consistent with the reference test file for the rnn classifier).

You need to define your dataset(classification_x) in tests/models/torch/conftest.py. If possible, use synthetic dataset for unit tests or use pre-availables from scikit-learn.

Examples:
Synthetic dataset: tests/models/torch/conftest.py:regression_data()
scikit-learn dataset: tests/models/river/test_linear_model.py classification_dataset(self)

2022-06-17 11:46 UTC, Christosc96 commented
I used the same dataset i used in the notebook, InceptionTime requires a bit of editing to data in order to be compatible with expected model dimensions so I put the dataset as a fixture in inception-time's own test file

2022-06-17 14:43 UTC, dhavalsalwala approved these changes
Looks Good to me.

2022-06-17 14:43 UTC, dhavalsalwala commented on sail/models/torch/inceptiontime.py
> +            device='cuda',
Make default value to cpu.

2022-06-17 14:43 UTC, dhavalsalwala commented on tests/models/torch/test_inceptiontime.py
> +        assert not np.allclose(y_pred, 0)
np is not defined.

2022-06-17 14:43 UTC, dhavalsalwala commented on tests/models/torch/test_inceptiontime.py
> +    def net_partial_fit(self, net, classification_x, classification_y):
classification_x is not defined.

2022-06-17 14:43 UTC, dhavalsalwala commented on tests/models/torch/test_inceptiontime.py
> +        return InceptionTimeClassifier(lr=0.07)
HI @Christosc96 ,
As per your code, it should be learning_rate instead of lr.

2022-06-17 14:46 UTC, merged